name: Test needs, skip(ped), and always()

on:
  workflow_dispatch:

jobs:
  # Step 1: Start somewhere
  start-here:
    name: Start here
    runs-on: ubuntu-latest
    steps:
      - run: echo 'start-here'

  # Step 2-1: Build. Or skip the build if the artifact can be grabbed from somewhere else.
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: start-here
    steps:
      - run: echo 'build'

  skip-build:
    name: Skip Build
    runs-on: ubuntu-latest
    needs: start-here
    if: false
    steps:
      - run: echo 'skip-build'

  # Step 2-2: Lint.
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: start-here
    steps:
      - run: echo 'lint'

  # Step 3: Test the build.
  test:
    name: "Test"
    runs-on: ubuntu-latest
    needs: [build, lint]
    steps:
      - run: echo 'test'

  test-with-skip-build:
    name: "Test after Skip Build"
    runs-on: ubuntu-latest
    needs: [skip-build, lint]
    steps:
      - run: echo 'test-with-skip-build'

  always-test-with-skip-build:
    name: "Test with always() after Skip Build"
    runs-on: ubuntu-latest
    needs: [skip-build, lint]
    if: always()
    steps:
      - run: echo 'always-test-with-skip-build'

  # Step 5: Report.
  report:
    name: "Report"
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo 'report'

  report-with-skip-build:
    name: "Report after Skip Build"
    runs-on: ubuntu-latest
    needs: [test-with-skip-build]
    steps:
      - run: echo 'report-with-skip-build'

  always-report-with-skip-build:
    name: "Report with always() after Skip Buid"
    runs-on: ubuntu-latest
    needs: [always-test-with-skip-build]
    if: always()
    steps:
      - run: echo 'always-report-with-skip-build'

  job1:
    name: "Job 1 will run"
    runs-on: ubuntu-latest
    steps:
      - run: echo 'job1'

  job2:
    name: "Job 2 might skip"
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo 'job2'

  needs-job1-job2:
    name: "Needs Job 1 and Job 2"
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - run: echo 'needs-job1-job2'
  
  always-needs-job1-job2:
    name: "always() needs Job 1 and Job 2"
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: always()
    steps:
      - run: echo 'always-needs-job1-job2'

  always-needs-job1-job2-skipped:
    name: "Needs Job 1 and Job 2"
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: always() && needs.job2.result == 'skipped'
    steps:
      - run: echo 'Job 2 skipped'
  
  job3-job2-skipped:
    name: "After Job 2 skipped"
    runs-on: ubuntu-latest
    needs: [always-needs-job1-job2-skipped]
    steps:
      - run: echo 'Job 3 aftr Job 2 skipped'

  always-job3-job2-skipped:
    name: "After Job 2 skipped"
    runs-on: ubuntu-latest
    needs: [always-needs-job1-job2-skipped]
    if: always()
    steps:
      - run: echo 'always() with Job 3 aftr Job 2 skipped'