name: Test needs, skip(ped), and always()

on:
  workflow_dispatch:

jobs:
  # Step 1: Start somewhere
  start-here:
    name: Start here
    runs-on: ubuntu-latest
    steps:
      - run: echo 'start-here'

  # Step 2-1: Build. Or skip the build if the artifact can be grabbed from somewhere else.
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: start-here
    steps:
      - run: echo 'build'

  skip-build:
    name: Skip Build
    runs-on: ubuntu-latest
    needs: start-here
    if: false
    steps:
      - run: echo 'skip-build'

  # Step 2-2: Lint.
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: start-here
    steps:
      - run: echo 'lint'

  # Step 3: Test the build.
  test:
    name: "Test"
    runs-on: ubuntu-latest
    needs: [build, lint]
    steps:
      - run: echo 'test'

  test-with-skip-build:
    name: "Test after Skip Build"
    runs-on: ubuntu-latest
    needs: [skip-build, lint]
    steps:
      - run: echo 'test-with-skip-build'

  always-test-with-skip-build:
    name: "Test with always() after Skip Build"
    runs-on: ubuntu-latest
    needs: [skip-build, lint]
    if: always()
    steps:
      - run: echo 'always-test-with-skip-build'

  # Step 5: Report.
  report:
    name: "Report"
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo 'report'

  report-with-skip-build:
    name: "Report after Skip Build"
    runs-on: ubuntu-latest
    needs: [test-with-skip-build]
    steps:
      - run: echo 'report-with-skip-build'

  always-report-with-skip-build:
    name: "Report with always() after Skip Buid"
    runs-on: ubuntu-latest
    needs: [always-test-with-skip-build]
    if: always()
    steps:
      - run: echo 'always-report-with-skip-build'
