name: Skip status

on:
  workflow_dispatch:

jobs:
  skip-job:
    name: 'Skipped job'
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo 'Skipped job'

  skip-steps:
    name: 'Skipped steps'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Skipped step 1'
        if: false
      - run: echo 'Skipped step 2'
        if: false
      - run: echo 'Skipped step 3'
        if: false

  after:
    name: 'After'
    runs-on: ubuntu-latest
    needs: [skip-job, skip-steps]
    if: always()
    steps:
      - run: echo 'After'
