name: Test skipping jobs

on:
  workflow_dispatch:

jobs:
  start-here:
    name: Start here
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Start here'

  job-that-skips:
    name: Job that skips
    runs-on: ubuntu-latest
    needs: start-here
    if: false
    steps:
      - run: echo 'This should skip'

  job-that-runs:
    name: Job that runs
    runs-on: ubuntu-latest
    needs: start-here
    steps:
      - run: echo 'This should run'

  try-needs:
    name: Needs
    runs-on: ubuntu-latest
    needs: [job-that-skips, job-that-runs]
    steps:
      - run: echo 'One job passed, so this should run'

  try-results:
    name: See if things worked with results
    runs-on: ubuntu-latest
    needs: [job-that-skips, job-that-runs]
    if: needs.job-that-skip.result == 'skipped' && needs.job-that-runs == 'success'
    steps:
      - run: echo 'Both results are true, so this should run'

  always-run:
    name: Always run this job
    runs-on: ubuntu-latest
    needs: [job-that-skips, job-that-runs]
    if: always()
    steps:
      - run: echo 'This should run'

  try-after-always-run:
    name: always-run succeeded, so this should run
    runs-on: ubuntu-latest
    needs: [always-run]
    steps:
      - run: echo 'This should run'

  try-always-with-conditional:
    name: See if things worked with always and result conditionals
    runs-on: ubuntu-latest
    needs: [job-that-skips, job-that-runs]
    if: always() && needs.job-that-skips.result == 'skipped' && needs.job-that-runs.result == 'success'
    steps:
      - run: echo 'This should run'

  try-after-always-with-conditional:
    name: try-always-with-conditional succeeded, so this should run
    runs-on: ubuntu-latest
    needs: [try-always-with-conditional]
    steps:
      - run: echo 'This should run'

  # https://stackoverflow.com/questions/74386773/github-actions-job-is-skipped-although-all-needs-succeeded/74529413#74529413
  try-undocumented-success-string-parameter:
    name: Use undocumented success(string)
    runs-on: ubuntu-latest
    needs: [job-that-skips, job-that-runs]
    if: success('job-that-runs')
    steps:
      - run: echo 'This should run'
