name: Skip status

on:
  workflow_dispatch:

jobs:
  skip-job:
    name: 'Skipped job'
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo 'Skipped job'

  skip-steps:
    name: 'Skipped steps'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Skipped step 1'
        if: false
      - run: echo 'Skipped step 2'
        if: false
      - run: echo 'Skipped step 3'
        if: false

  after-skip-job:
    name: 'After'
    runs-on: ubuntu-latest
    needs: [skip-job]
    steps:
      - run: echo 'After skip-job'

  after-skip-steps:
    name: 'After skip-steps'
    runs-on: ubuntu-latest
    needs: [skip-steps]
    steps:
      - run: echo 'After skip-steps'

  after-all:
    name: 'After all'
    runs-on: ubuntu-latest
    needs: [skip-job, skip-steps]
    steps:
      - run: echo 'After all'
